#!/usr/bin/awk -f 

function red(s) {
    printf "\033[1;31m" s "\033[0m "
}

function green(s) {
    printf "\033[1;32m" s "\033[0m "
}

function blue(s) {
    printf "\033[1;34m" s "\033[0m "
}

function detectNic( ) {
	printf "Enter the Ethernet card to listen or press enter to listen to Default:";getline nic<"/dev/tty"
	if (nic == ""){

		command = "cat /var/defaultnic"

    		nic = command | getline
		print "Default network card to listen: " $nic 		
		return $nic

			}
		else{	
		return nic
		}

}
BEGIN{
    
    nic = detectNic();
    cmd = "tcpdump -nv -s 1500 ether dst 01:00:0c:cc:cc:cc -c 1 -i"

    while ((cmd nic | getline) > 0) {
	str="Device-ID:Cisco IOS Software:Port-ID:VTP:Address:VLAN:Duplex:VoIP:"
  	split(str,s,":")

  	for(i=1;i<=length(s);i++){
   		if ($0 ~ s[i] && s[i]){

#DEVICE ID
      			if (i==1){            
				print "\n";	
				print red("Device Name: ") green($7);
				}	

#SOFTWARE VERSION      
      			else if (i==2){                          
				print red("Software Version: ") green($0) ;
					}

#PORT      
      			else if (i==3){                      
				print red($1 ": ") green($7);
					}
#VTP DOMAIN	
			else if (i==4){                             
				print red($1 " " $2 " " $3 ": ") green($9);
					}

#IP ADDRESS
		        else if (i==5){                             
				print red("IP Address: ") green($9);
					}

#CURRENT VLAN     
			else if (i==6){                                 
				print red("VLAN: ") green($9);
					}

#DUPLEX
			else if (i==7){                                
				print red("DUPLEX: ") green($7);
					}

#VOICE VLAN
    			else if (i==8){                                 
				print red("Voice VLAN: ") green($13);
					}

			else{ 
      				s[i]=0;print "   "}
    			    }  
  				}
			}
	}		

