#!/usr/bin/awk -f

#this script requires that you have tcpdump and that it is enables to run without root.
#to run tcpdump without root do:
#sudo chown -R root tcpdump
#sudo chmod 4555 tcpdump

function red(s) {
    printf "\033[1;31m" s "\033[0m "
}

function green(s) {
    printf "\033[1;32m" s "\033[0m "
}

function blue(s) {
    printf "\033[1;34m" s "\033[0m "
}


BEGIN{

    cmd = "tcpdump -nvi enp0s25 -s 1500 ether dst 01:00:0c:cc:cc:cc -c 1"
    while ((cmd | getline) > 0) {
	str="Device-ID:Cisco IOS Software:Port-ID:VTP:Address:VLAN:Duplex:VoIP:"
  	split(str,s,":")

  	for(i=1;i<=length(s);i++){
   		if ($0 ~ s[i] && s[i]){

      			if (i==1){             /* device id*/
				print "\n";	
				print red("Device Name: ") green($7);
				}	
      
      			else if (i==2){                          /* Software Version*/
				print red("Software Version: ") green($0) ;
					}
      
      			else if (i==3){                      /*Port*/
				print red($1 ": ") green($7);
					}
	
			else if (i==4){                               /* vtp management domain*/
				print red($1 " " $2 " " $3 ": ") green($9);
					}

		        else if (i==5){                              /* IP address*/
				print red("IP Address: ") green($9);
					}
     
			else if (i==6){                                 /* current vlan */
				print red("VLAN: ") green($9);
					}

			else if (i==7){                                 /* duplex */
				print red("DUPLEX: ") green($7);
					}
    			else if (i==8){                                 /* Voice Vlan */
				print red("Voice VLAN: ") green($13);
					}

			else{ 
      				s[i]=0;print "   "}
    			    }  
  				}
			}
	}		

